# Generated by Django 5.0.4 on 2024-05-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veraz', '0003_datos_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cuil', models.CharField(max_length=11)),
            ],
        ),
        migrations.AlterField(
            model_name='datos',
            name='archivo',
            field=models.FileField(null=True, upload_to='archivos/'),
        ),
    ]
