# Generated by Django 5.0.4 on 2024-05-13 23:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veraz', '0004_registrohistorial_alter_datos_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='archivo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='archivos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datos',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datos',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datos',
            name='numero_gestion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
