# Generated by Django 5.0.4 on 2024-07-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veraz', '0005_alter_datos_archivo_alter_datos_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='datos',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='datos',
            name='email',
        ),
        migrations.RemoveField(
            model_name='datos',
            name='numero_gestion',
        ),
        migrations.AddField(
            model_name='datos',
            name='cuil',
            field=models.CharField(default='12345678', max_length=11),
        ),
        migrations.AddField(
            model_name='datos',
            name='telefono',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
