# Generated by Django 5.1.4 on 2024-12-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veraz', '0006_remove_datos_archivo_remove_datos_direccion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formulario',
        ),
        migrations.DeleteModel(
            name='RegistroHistorial',
        ),
        migrations.AddField(
            model_name='datos',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=100),
        ),
    ]
