# Generated by Django 5.1.4 on 2024-12-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veraz', '0007_delete_formulario_delete_registrohistorial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(default='12345678', max_length=8)),
                ('cuil', models.CharField(default='12345678', max_length=11)),
                ('telefono', models.CharField(default='0000000000', max_length=20)),
                ('email', models.EmailField(default='example@example.com', max_length=100)),
                ('detalles_deudas', models.TextField(default='')),
            ],
        ),
    ]
